// database/generate-seed.js
//
// Generates ~5,000 SYNTHETIC laptop product records with realistic
// value distributions (real brand names, real processor families,
// price correlated with specs). This data is NOT real market data —
// it exists solely to give us enough rows to make search, filtering,
// sorting, pagination, and indexing experiments meaningful.

const fs = require('fs');

const brands = ['Dell', 'HP', 'Lenovo', 'Asus', 'Acer', 'Apple', 'MSI', 'Samsung'];

const processorsByTier = {
  entry: ['Intel Core i3-1215U', 'AMD Ryzen 3 7320U', 'Intel Core i3-1315U'],
  mid: ['Intel Core i5-1335U', 'AMD Ryzen 5 7530U', 'Intel Core i5-13500H', 'Apple M2'],
  high: ['Intel Core i7-13700H', 'AMD Ryzen 7 7735HS', 'Apple M3 Pro', 'Intel Core i7-1355U'],
  premium: ['Intel Core i9-13900H', 'AMD Ryzen 9 7940HS', 'Apple M3 Max']
};

const gpusByTier = {
  entry: ['Integrated', 'Intel UHD Graphics'],
  mid: ['Integrated', 'NVIDIA GeForce RTX 3050'],
  high: ['NVIDIA GeForce RTX 4060', 'NVIDIA GeForce RTX 4050', 'AMD Radeon RX 6600M'],
  premium: ['NVIDIA GeForce RTX 4080', 'NVIDIA GeForce RTX 4090', 'Integrated (Apple GPU)']
};

const categories = ['Ultrabook', 'Gaming Laptop', 'Business Laptop', 'Budget Laptop', '2-in-1 Convertible'];
const storageTypes = ['SSD', 'HDD', 'SSD+HDD'];
const resolutions = ['1366x768', '1920x1080', '2560x1440', '3840x2160'];
const operatingSystems = ['Windows 11', 'Windows 10', 'macOS', 'Chrome OS', 'Linux'];

function randInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randFloat(min, max, decimals) {
  const val = Math.random() * (max - min) + min;
  return parseFloat(val.toFixed(decimals));
}

function pick(arr) {
  return arr[randInt(0, arr.length - 1)];
}

function pickTier() {
  const roll = Math.random();
  if (roll < 0.30) return 'entry';
  if (roll < 0.65) return 'mid';
  if (roll < 0.90) return 'high';
  return 'premium';
}

function escapeSql(value) {
  if (value === null) return 'NULL';
  if (typeof value === 'string') return `'${value.replace(/'/g, "''")}'`;
  return value;
}

const rows = [];
const TOTAL_ROWS = 5000;

for (let i = 0; i < TOTAL_ROWS; i++) {
  const tier = pickTier();
  const brand = pick(brands);
  const model = `${brand.slice(0, 3).toUpperCase()}-${randInt(1000, 9999)}`;
  const category = pick(categories);
  const processor = pick(processorsByTier[tier]);
  const gpu = Math.random() < 0.9 ? pick(gpusByTier[tier]) : null; // ~10% missing, realistic
  const ram_gb = pick([8, 16, 32, 64].filter(r =>
    tier === 'entry' ? r <= 16 :
    tier === 'mid' ? r <= 32 :
    true
  ));
  const storage_gb = pick([256, 512, 1024, 2048].filter(s =>
    tier === 'entry' ? s <= 512 : true
  ));
  const storage_type = pick(storageTypes);

  // Base price correlated with tier + specs, plus random noise
  const tierBase = { entry: 35000, mid: 60000, high: 95000, premium: 150000 }[tier];
  const ramFactor = ram_gb * 350;
  const storageFactor = storage_gb * 8;
  const price = Math.round(tierBase + ramFactor + storageFactor + randInt(-5000, 8000));

  const rating = randFloat(2.5, 5.0, 1);
  const review_count = randInt(0, 3000);
  const screen_size = Math.random() < 0.95 ? randFloat(13.0, 17.3, 1) : null; // ~5% missing
  const resolution = Math.random() < 0.95 ? pick(resolutions) : null;
  const operating_system = Math.random() < 0.97 ? pick(operatingSystems) : null;
  const battery_life_hours = Math.random() < 0.9 ? randFloat(4.0, 18.0, 1) : null;
  const weight_kg = Math.random() < 0.9 ? randFloat(1.1, 3.2, 2) : null;
  const stock_quantity = randInt(0, 500);

  rows.push([
    brand, model, category, price, rating, review_count, processor,
    ram_gb, storage_gb, storage_type, gpu, screen_size, resolution,
    operating_system, battery_life_hours, weight_kg, stock_quantity
  ]);
}

const columns = [
  'brand', 'model', 'category', 'price', 'rating', 'review_count', 'processor',
  'ram_gb', 'storage_gb', 'storage_type', 'gpu', 'screen_size', 'resolution',
  'operating_system', 'battery_life_hours', 'weight_kg', 'stock_quantity'
];

let sql = `-- database/seed.sql
-- AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
-- Generated by database/generate-seed.js
--
-- IMPORTANT: This data is SYNTHETIC. It is generated with realistic
-- value distributions (real brand names, real processor families,
-- price correlated with specs) but does NOT represent real products,
-- real prices, or real market data. It exists solely to provide a
-- dataset large enough to make search/filter/sort/pagination/indexing
-- experiments meaningful.

TRUNCATE TABLE products RESTART IDENTITY;

`;

const BATCH_SIZE = 500;
for (let i = 0; i < rows.length; i += BATCH_SIZE) {
  const batch = rows.slice(i, i + BATCH_SIZE);
  const valuesSql = batch.map(row =>
    `(${row.map(escapeSql).join(', ')})`
  ).join(',\n');

  sql += `INSERT INTO products (${columns.join(', ')}) VALUES\n${valuesSql};\n\n`;
}

fs.writeFileSync('database/seed.sql', sql);
console.log(`Generated ${TOTAL_ROWS} synthetic rows into database/seed.sql`);